name: Auto Build All Bundles

# To use this workflow the BUILD_TOKEN secret should be configured

on: [push]
jobs:
  Run-Build-Linux:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: ubuntu-latest
      git_branch: fixes_3_2
      bundle_name: fpc-fixes_3_2.x86_64-linux
    secrets: inherit
  Run-Build-Windows:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: windows-latest
      git_branch: fixes_3_2
      bundle_name: fpc-fixes_3_2.x86_64-windows
    secrets: inherit
  Run-Build-macOS:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: macos-latest
      git_branch: main
      bundle_name: fpc-fixes_3_2.x86_64-macos
      fpc_opt: "-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
    secrets: inherit
