name: Auto Build All Bundles
on: [push]
jobs:
  Run-Building-Bundle:
    runs-on: ubuntu-latest
    steps:
      - name: "Build 3.2.1 for Linux x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from SVN
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "os": "ubuntu-latest", "branch": "branches/fixes_3_2", "bundle_name": "fpc-3.2.3.x64-linux"}'
      - name: "Build 3.2.1 for Windows x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from SVN
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "os": "windows-latest", "branch": "branches/fixes_3_2", "bundle_name": "fpc-3.2.3.x64-windows"}'
      - name: "Build 3.2.1 for macOS x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from SVN
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "os": "macos-latest", "branch": "branches/fixes_3_2", "bundle_name": "fpc-3.2.3.x64-macos"}'
