name: Auto Build All Bundles

# To use this workflow the BUILD_TOKEN secret should be configured

on: [push]
jobs:
  Build-Windows-3_2:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: windows-latest
      git_branch: fixes_3_2
      bundle_name: fpc-fixes_3_2.x86_64-windows
    secrets: inherit
  Build-Linux-3_2:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: ubuntu-latest
      git_branch: fixes_3_2
      bundle_name: fpc-fixes_3_2.x86_64-linux
    secrets: inherit
  Build-Windows-main:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: windows-latest
      git_branch: main
      bundle_name: fpc-main.x86_64-windows
    secrets: inherit
  Build-macOS-main:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: macos-latest
      git_branch: main
      bundle_name: fpc-fixes_3_2.x86_64-macos
      fpc_opt: "-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
      fpc_version: 3.3.1
    secrets: inherit

  Final:
    if: always()
    needs: [Build-Windows-3_2, Build-Linux-3_2, Build-Windows-main, Build-macOS-main]
    steps:
      - run: echo "# 🎉 Auto builds have been finished!" >>$GITHUB_STEP_SUMMARY
