name: Auto Build All Bundles

# To use this workflow the BUILD_TOKEN secret should be configured

on: [push]
jobs:
  Run-Building-Bundle:
    runs-on: ubuntu-latest
    steps:
      - name: "Build latest FPC for Linux x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from GIT
          token: ${{ secrets.BUILD_TOKEN }}
          inputs: '{ "os": "ubuntu-latest", "bundle_name": "fpc-latest.x64-linux" }'
      - name: "Build latest FPC for Windows x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from GIT
          token: ${{ secrets.BUILD_TOKEN }}
          inputs: '{ "os": "windows-latest", "bundle_name": "fpc-latest.x64-windows" }'
      - name: "Build latest FPC for macOS x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from GIT
          token: ${{ secrets.BUILD_TOKEN }}
          inputs: '{ "os": "macos-latest", "bundle_name": "fpc-latest.x64-macos" }'
