name: Auto Build All Bundles

# To use this workflow the BUILD_TOKEN secret should be configured

on: 
  push:
  schedule:
    - cron: '* 0/6 * * *'
jobs:
  Build-3_2_3:
    uses: ./.github/workflows/build-3-2-3.yml
    secrets: inherit
  Build-main:
    uses: ./.github/workflows/build-main.yml
    secrets: inherit

  Final:
    if: always()
    needs: [Build-3_2_3, Build-main]
    runs-on: ubuntu-latest
    steps:
      - run: echo "# 🎉 Auto builds have been finished! 🎉" >>$GITHUB_STEP_SUMMARY
