name: Auto Build All Bundles

# To use this workflow the BUILD_TOKEN secret should be configured

on: [push]
jobs:
  Run-Building-Bundle:
    runs-on: ubuntu-latest
    steps:
      - name: "Build stable FPC for Linux x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from GIT
          token: ${{ secrets.BUILD_TOKEN }}
          inputs: '{ "os": "ubuntu-latest", "git_branch": "fixes_3_2", "bundle_name": "fpc-fixes_3_2.x64-linux" }'
      - name: "Build stable FPC for Windows x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from GIT
          token: ${{ secrets.BUILD_TOKEN }}
          inputs: '{ "os": "windows-latest", "git_branch": "fixes_3_2", "bundle_name": "fpc-fixes_3_2.x64-windows" }'
      - name: "Build stable FPC for macOS x64"
        if: ${{ always() }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build FPC bundle from GIT
          token: ${{ secrets.BUILD_TOKEN }}
          inputs: '{ "os": "macos-latest", "git_branch": "fixes_3_2", "bundle_name": "fpc-fixes_3_2.x64-macos" }'
