name: Build FPC 3.2.3

on:
  workflow_dispatch:
    inputs:
      release_to:
        description: 'Release to the specified tag (if needed)'
        required: false
        default: ''
  workflow_call:

jobs:
  Windows-3_2_3:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: windows-latest
      git_branch: fixes_3_2
      bundle_name: fpc-3.2.3-Windows
    secrets: inherit
  Linux-3_2_3:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: ubuntu-latest
      git_branch: fixes_3_2
      bundle_name: fpc-3.2.3-Linux
    secrets: inherit
  macOS-3_2_3:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: macos-latest
      git_branch: fixes_3_2
      bundle_name: fpc-3.2.3-macOS
      fpc_opt: "-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
    secrets: inherit
