name: Build main (development) FPC

on:
  workflow_dispatch:
    inputs:
      release_to:
        description: 'Release to the specified tag (if needed)'
        required: false
        default: ''
  workflow_call:

jobs:
  Windows-main:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: windows-latest
      git_branch: main
      bundle_name: fpc-3.3.1-Windows
      fpc_version: 3.3.1
    secrets: inherit
  Linux-main:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: ubuntu-latest
      git_branch: main
      bundle_name: fpc-3.2.3-Linux
      fpc_version: 3.3.1
    secrets: inherit
  macOS-main:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: macos-latest
      git_branch: main
      bundle_name: fpc-3.3.1-macOS
      fpc_opt: "-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
      fpc_version: 3.3.1
    secrets: inherit
