name: Build FPC bundle from GIT

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'GitHub environment (e.g. ubuntu-latest, windows-latest, macos-latest)'
        required: true
      fpc:
        description: 'Compiler version ("system" is for installing from packet manager)'
        required: false
        default: 'system'
      fpc_opt:
        description: 'Additional options for build process'
        required: false
        default: ''
      git_url:
        description: 'GIT url of sources'
        required: false
        default: 'https://gitlab.com/freepascal.org/fpc/source.git'
      git_branch:
        description: 'Branch'
        required: false
        default: 'main'
      bundle_name:
        description: 'Bundle name'
        required: false
        default: 'bundle'
      cross_compilers:
        description: 'Build cross compilers'
        required: false
        default: 'true'
jobs:
  Build-Bundle:
    name: "Build FPC for ${{ github.event.inputs.os }} from ${{ github.event.inputs.git_url }}"
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Install Free Pascal Compiler (apt-get)
        if: (runner.os == 'Linux') && (github.event.inputs.fpc == 'system')
        run: sudo apt-get install fpc

      - name: Install Free Pascal Compiler (choco)
        if: (runner.os == 'Windows') && (github.event.inputs.fpc == 'system')
        run: |
          choco install freepascal
          refreshenv

      - name: Workaround for missed PATH settings (choco)
        if: (runner.os == 'Windows') && (github.event.inputs.fpc == 'system')
        run: |
          ls "C:\\tools\\freepascal"
          ls "C:\\tools\\freepascal\\bin"
          ls "C:\\tools\\freepascal\\bin\\i386-win32"
          echo "C:\\tools\\freepascal\\bin\\i386-win32" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Free Pascal Compiler (brew)
        if: (runner.os == 'macOS') && (github.event.inputs.fpc == 'system')
        run: |
          brew update
          brew install fpc

      - name: Install Free Pascal Compiler (GitHub Action)
        if: github.event.inputs.fpc == 'setup-fpc'
        uses: visualdoj/setup-fpc@v0.1.11-beta

      - name: Print FPC version
        run: fpc -i

      - name: Get FPC sources
        working-directory: "${{ github.workspace }}"
        run: git clone --branch "${{ github.event.inputs.git_branch }}" "${{ github.event.inputs.git_url }}" src

      - name: Copy FPC source before it will have been polluted
        working-directory: "${{ github.workspace }}/src"
        run: git checkout-index --prefix="${{ github.workspace }}/bundle/src/" -a

      - name: Copy binutils (Windows)
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}/bundle"
        run: |
          mkdir installed
          mkdir installed\bin
          mkdir installed\bin\i386-win32
          cp C:\tools\freepascal\bin\i386-win32\* installed\bin\i386-win32\

      - name: Build FPC
        working-directory: "${{ github.workspace }}/src"
        run: make build OPT="${{ github.event.inputs.fpc_opt }}"

      - name: Install FPC
        working-directory: "${{ github.workspace }}/src"
        run: make install PREFIX="${{ github.workspace }}/bundle/installed"

      - name: Generate info
        working-directory: "${{ github.workspace }}/bundle"
        run: |
            mkdir info
            fpc -i >info/fpc-version.txt

      - name: Tar the bundle
        working-directory: "${{ github.workspace }}"
        run: tar -cvf bundle.tar bundle/*

      - name: Upload the bundle
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.event.inputs.bundle_name }}"
          path: "${{ github.workspace }}/bundle.tar"

  Build-Bundle-Cross:
    name: "Build FPC cross compilers"
    if: github.event.inputs.cross_compilers != ''
    needs: Build-Bundle
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - name: Download FPC bundle
        uses: actions/download-artifact@v3
        id: download
        with:
            name: "${{ github.event.inputs.bundle_name }}"
            path: "${{ github.workspace }}"

      - name: Install GNU Core Utils (choco)
        if: runner.os == 'Windows'
        run: |
          choco install gnuwin32-coreutils.install
          make --version

      - name: List files
        working-directory: "${{ github.workspace }}"
        run: ls -R

      - name: Untar the bundle
        working-directory: "${{ github.workspace }}"
        run: |
            tar xvf bundle.tar
            mv bundle fpc

      - name: Get binutils
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}"
        run: git clone "https://gitlab.com/freepascal.org/fpc/binaries.git" fpc-binaries

      - name: Setup FPC PATH (Windows)
        if: runner.os == 'Windows'
        run: echo ${{ github.workspace }}\fpc\installed\bin\i386-win32 | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Print FPC version
        run: fpc -i

      - name: Create cross bundle
        working-directory: "${{ github.workspace }}"
        run: |
            mkdir bundle-cross
            cp -r fpc/* bundle-cross/

      - name: Copy binutils (Windows)
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}/fpc-binaries/i386-win32"
        run: git checkout-index --prefix="${{ github.workspace }}/bundle-cross/installed/bin/i386-win32/" -a

      - name: Setup binutils PATH (Windows)
        if: runner.os == 'Windows'
        run: echo ${{ github.workspace }}\fpc-binaries\i386-win32 | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Android NDK (choco)
        if: runner.os == 'Windows'
        run: |
          choco install android-ndk --params="'/InstallationPath:${{ github.workspace }}\Android\'"
          refreshenv

      - name: Build FPC cross compiler (windows to win64)
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}/fpc/src"
        run: |
            make clean all OS_TARGET=win64 CPU_TARGET=x86_64 OPT="${{ github.event.inputs.fpc_opt }}" PREFIX="${{ github.workspace }}/bundle-cross/installed"
            make crossinstall OS_TARGET=win64 CPU_TARGET=x86_64 PREFIX="${{ github.workspace }}/bundle-cross/installed"

      - name: Build FPC cross compiler (windows to x86_64-linux)
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}/fpc/src"
        run: |
            make clean all OS_TARGET=linux CPU_TARGET=x86_64 OPT="${{ github.event.inputs.fpc_opt }}" PREFIX="${{ github.workspace }}/bundle-cross/installed"
            make crossinstall OS_TARGET=linux CPU_TARGET=x86_64 PREFIX="${{ github.workspace }}/bundle-cross/installed"

      - name: Build FPC cross compiler (windows to android)
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}/fpc/src"
        run: |
            set PATH=%PATH%;${{ github.workspace }}/src
            make clean crossall crossinstall OS_TARGET=android CPU_TARGET=arm CROSSOPT="-Cparmv7a -Cfvfpv3" INSTALL_PREFIX="${{ github.workspace }}/bundle-cross/installed"

      - name: Tar the cross bundle
        working-directory: "${{ github.workspace }}"
        run: tar -cvf bundle-cross.tar bundle-cross/*

      - name: Upload the cross bundle
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.event.inputs.bundle_name }}-cross"
          path: "${{ github.workspace }}/bundle-cross.tar"
