name: Build FPC bundle from GIT
run-name: "${{ inputs.os }}"

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'GitHub environment (e.g. ubuntu-latest, windows-latest, macos-latest)'
        required: true
      fpc:
        description: 'Compiler version ("system" is for installing FPC from packet manager)'
        required: false
        default: 'setup-fpc'
      fpc_opt:
        description: 'Additional options for build process'
        required: false
        default: ''
      git_url:
        description: 'GIT url of sources'
        required: false
        default: 'https://gitlab.com/freepascal.org/fpc/source.git'
      git_branch:
        description: 'Branch'
        required: false
        default: 'main'
      bundle_name:
        description: 'Bundle name'
        required: false
        default: 'bundle'
      fpc_version:
        description: 'FPC version'
        required: false
        default: '3.2.3'
      cross:
        description: 'Which cross crompilers build'
        required: false
        default: 'all'
  workflow_call:
    inputs:
      os:
        description: 'GitHub environment (e.g. ubuntu-latest, windows-latest, macos-latest)'
        type: string
        required: true
      fpc:
        description: 'Compiler version ("system" is for installing FPC from packet manager)'
        type: string
        required: false
        default: 'setup-fpc'
      fpc_opt:
        description: 'Additional options for build process'
        type: string
        required: false
        default: ''
      git_url:
        description: 'GIT url of sources'
        type: string
        required: false
        default: 'https://gitlab.com/freepascal.org/fpc/source.git'
      git_branch:
        description: 'Branch'
        type: string
        required: false
        default: 'main'
      bundle_name:
        description: 'Bundle name'
        type: string
        required: false
        default: 'bundle'
      fpc_version:
        description: 'FPC version'
        type: string
        required: false
        default: '3.2.3'
      cross:
        description: 'Which cross crompilers build'
        type: string
        required: false
        default: 'all'

jobs:
  Build-Bundle:
    name: "Host"
    runs-on: ${{ inputs.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Free Pascal Compiler (apt-get)
        if: (runner.os == 'Linux') && (inputs.fpc == 'system')
        run: sudo apt-get install fpc

      - name: Install Free Pascal Compiler (choco)
        if: (runner.os == 'Windows') && (inputs.fpc == 'system')
        run: |
          choco install freepascal --yes

      - name: Workaround for missing PATH settings (choco)
        if: (runner.os == 'Windows') && (inputs.fpc == 'system')
        run: |
          ls "C:\\tools\\freepascal"
          ls "C:\\tools\\freepascal\\bin"
          ls "C:\\tools\\freepascal\\bin\\i386-win32"
          echo "C:\\tools\\freepascal\\bin\\i386-win32" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Free Pascal Compiler (brew)
        if: (runner.os == 'macOS') && (inputs.fpc == 'system')
        run: |
          brew update
          brew install fpc

      - name: Install Free Pascal Compiler (GitHub Action)
        if: inputs.fpc == 'setup-fpc'
        uses: visualdoj/setup-fpc@main

      - name: Print FPC version
        run: fpc -i

      - name: Get FPC sources
        working-directory: "${{ github.workspace }}"
        run: git clone --branch "${{ inputs.git_branch }}" "${{ inputs.git_url }}" fpc_src

      - name: Copy FPC source before it will be polluted
        working-directory: "${{ github.workspace }}/fpc_src"
        run: git checkout-index --prefix="${{ github.workspace }}/bundle/src/" -a

      - name: Copy binutils (Windows)
        if: runner.os == 'Windows'
        working-directory: "${{ github.workspace }}"
        run: |
          mkdir installed
          mkdir installed\bin
          mkdir installed\bin\i386-win32
          git clone "https://gitlab.com/freepascal.org/fpc/binaries.git" fpc-binaries
          cd fpc-binaries && git checkout-index --prefix="${{ github.workspace }}/bundle/installed/bin/" -a

      - run: make --version

      - name: Build FPC
        working-directory: "${{ github.workspace }}/fpc_src"
        run: make build install OPT="${{ inputs.fpc_opt }}" PREFIX="${{ github.workspace }}/bundle/installed"

      - name: Copy gnu programs to fpc bin (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
            cp -r bin/i386-win32/* bundle/installed/bin/i386-win32/

      - name: fpc.cfg (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
             "${{ github.workspace }}\\bundle\\installed\\bin\\i386-win32\\fpcmkcfg.exe" -d basepath='$FPC_INSTALLED_DIR$' -o "${{ github.workspace }}/bundle/fpc.cfg"

      - name: fpc.cfg (non-Windows)
        if: runner.os != 'Windows'
        run: fpcmkcfg -d basepath="\$FPC_INSTALLED_DIR\$/lib/fpc/\$FPCVERSION\$" -o "${{ github.workspace }}/bundle/fpc.cfg"

      - name: Generate info
        working-directory: "${{ github.workspace }}/bundle"
        run: |
            mkdir info
            fpc -i >info/fpc-version.txt

      - name: Tar the bundle
        working-directory: "${{ github.workspace }}"
        run: tar -czvf "${{ inputs.bundle_name }}.tar.gz" bundle/*

      - name: Upload the bundle
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.bundle_name }}.tar.gz"
          path: "${{ github.workspace }}/${{ inputs.bundle_name }}.tar.gz"

      - name: Upload the bundle to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: "${{ inputs.bundle_name }}.tar.gz"
          file: "${{ github.workspace }}/${{ inputs.bundle_name }}.tar.gz"
          file_glob: true

  Prep:
    name: Prep
    if: inputs.cross != ''
    runs-on: ${{ inputs.os }}
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id:  generate-matrix
        run: echo "matrix=$(cat matrix.json)" >>$GITHUB_OUTPUT

  Build-Cross:
    name: "Cross"
    needs: [Build-Bundle, Prep]
    if: inputs.cross != ''
    runs-on: ${{ inputs.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        cpu: [""]
        os:  [""]
        opt: [""]
        necessary: [false]
        exclude:
          - cpu: ""
          - os:  ""
        include:
          - {cpu: i386,      os: linux}
          - {cpu: i386,      os: go32v2}
          - {cpu: i386,      os: win32}
          - {cpu: i386,      os: os2}
          - {cpu: i386,      os: freebsd}
          - {cpu: i386,      os: beos}
          - {cpu: i386,      os: haiku}
          - {cpu: i386,      os: netbsd}
          - {cpu: i386,      os: solaris}
          - {cpu: i386,      os: netware}
          - {cpu: i386,      os: openbsd}
          - {cpu: i386,      os: wdosx}
          - {cpu: i386,      os: darwin}
          - {cpu: i386,      os: emx}
          - {cpu: i386,      os: watcom}
          - {cpu: i386,      os: netwlibc}
          - {cpu: i386,      os: wince}
          - {cpu: i386,      os: embedded}
          - {cpu: i386,      os: symbian}
          - {cpu: i386,      os: nativent}
          - {cpu: i386,      os: iphonesim}
          - {cpu: i386,      os: android}
          - {cpu: i386,      os: aros}
          - {cpu: m68k,      os: linux,        crossopt: -Cp68000}
          - {cpu: m68k,      os: netbsd,       crossopt: -Cp68000}
          - {cpu: m68k,      os: amiga,        crossopt: -Cp68000}
          - {cpu: m68k,      os: atari,        crossopt: -Cp68000}
          - {cpu: m68k,      os: palmos,       crossopt: -Cp68000}
          - {cpu: m68k,      os: macosclassic, crossopt: -Cp68000}
          - {cpu: m68k,      os: embedded,     crossopt: -Cp68000}
          - {cpu: m68k,      os: sinclairql,   crossopt: -Cp68000}
          - {cpu: powerpc,   os: linux}
          - {cpu: powerpc,   os: netbsd}
          - {cpu: powerpc,   os: amiga}
          - {cpu: powerpc,   os: macosclassic}
          - {cpu: powerpc,   os: darwin}
          - {cpu: powerpc,   os: morphos}
          - {cpu: powerpc,   os: embedded}
          - {cpu: powerpc,   os: wii}
          - {cpu: powerpc,   os: aix}
          - {cpu: sparc,     os: linux}
          - {cpu: sparc,     os: netbsd}
          - {cpu: sparc,     os: solaris}
          - {cpu: sparc,     os: embedded}
          - {cpu: x86_64,    os: linux}
          - {cpu: x86_64,    os: freebsd}
          - {cpu: x86_64,    os: haiku}
          - {cpu: x86_64,    os: netbsd}
          - {cpu: x86_64,    os: solaris}
          - {cpu: x86_64,    os: openbsd}
          - {cpu: x86_64,    os: darwin}
          - {cpu: x86_64,    os: win64}
          - {cpu: x86_64,    os: embedded}
          - {cpu: x86_64,    os: iphonesim}
          - {cpu: x86_64,    os: android}
          - {cpu: x86_64,    os: aros}
          - {cpu: x86_64,    os: dragonfly}
          - {cpu: arm,       os: linux,     opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: netbsd,    opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: palmos,    opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: wince,     opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: gba,       opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: nds,       opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: embedded,  opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: symbian,   opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: android,   opt: "-dFPC_ARMEL", crossopt: "-Cparmv7a -Cfvfpv3"}
          - {cpu: arm,       os: aros,      opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: freertos,  opt: "-dFPC_ARMEL"}
          - {cpu: arm,       os: ios,       opt: "-dFPC_ARMEL"}
          - {cpu: powerpc64, os: linux}
          - {cpu: powerpc64, os: darwin}
          - {cpu: powerpc64, os: embedded}
          - {cpu: powerpc64, os: aix}
          - {cpu: avr,       os: embedded,  make_opt: SUBARCH=avr35}
          - {cpu: armeb,     os: linux}
          - {cpu: armeb,     os: embedded}
          - {cpu: mips,      os: linux}
          - {cpu: mipsel,    os: linux}
          - {cpu: mipsel,    os: embedded}
          - {cpu: mipsel,    os: android}
          - {cpu: mips64,    os: linux}
          - {cpu: mips64el,  os: linux}
          - {cpu: jvm,       os: java}
          - {cpu: jvm,       os: android}
          - {cpu: i8086,     os: embedded}
          - {cpu: i8086,     os: msdos}
          - {cpu: i8086,     os: win16}
          - {cpu: aarch64,   os: linux}
          - {cpu: aarch64,   os: freebsd}
          - {cpu: aarch64,   os: darwin}
          - {cpu: aarch64,   os: win64}
          - {cpu: aarch64,   os: embedded}
          - {cpu: aarch64,   os: android}
          - {cpu: aarch64,   os: ios}
          - {cpu: wasm32,    os: embedded, opt: "BINUTILSPREFIX= OPT=\"-O-\" PP=fpc"}
          - {cpu: wasm32,    os: wasi,     opt: "BINUTILSPREFIX= OPT=\"-O-\" PP=fpc"}
          - {cpu: sparc64,   os: linux}
          - {cpu: riscv32,   os: linux}
          - {cpu: riscv32,   os: embedded}
          - {cpu: riscv32,   os: freertos}
          - {cpu: riscv64,   os: linux}
          - {cpu: riscv64,   os: embedded}
          - {cpu: xtensa,    os: linux}
          - {cpu: xtensa,    os: embedded}
          - {cpu: xtensa,    os: freertos}
          - {cpu: z80,       os: embedded}
          - {cpu: z80,       os: zxspectrum}
          - {cpu: z80,       os: msxdos}
          - {cpu: z80,       os: amstradcpc}
          - {cpu: loongarch64, os: linux}

    steps:
      - run: echo "${{ needs.Prep.outputs.matrix }}"

      - name: Check out
        uses: actions/checkout@v3

      - name: Download FPC bundle
        uses: actions/download-artifact@v3
        id: download
        with:
            name: "${{ inputs.bundle_name }}.tar.gz"
            path: "${{ github.workspace }}"

      - name: Untar the bundle
        working-directory: "${{ github.workspace }}"
        run: |
            tar zxvf "${{ inputs.bundle_name }}.tar.gz"
            mv bundle fpc

      - name: Add FPC to PATH (non-windows)
        if: runner.os != 'Windows'
        run: |
            echo  "${{ github.workspace }}/fpc/installed/bin" >> $GITHUB_PATH
            echo  "${{ github.workspace }}/fpc/installed/lib/fpc/${{ inputs.fpc_version }}" >> $GITHUB_PATH

      - name: Copy cross tools
        if: runner.os != 'Windows'
        run: |
            cp -r ${{ github.workspace }}/src/cross/* ${{ github.workspace }}/fpc/installed/bin/

      - name: Create cross bundle
        working-directory: "${{ github.workspace }}"
        run: |
            mkdir bundle-cross
            mkdir bundle-cross/installed
            mkdir bundle-cross/info

      - name: List files
        working-directory: "${{ github.workspace }}"
        run: ls -R

      - name: "${{ matrix.cpu }}-${{ matrix.os }}"
        id: prerequisites
        uses: ./.github/actions/setup-cross-prerequisites
        with:
          target_cpu: ${{ matrix.cpu }}
          target_os:  ${{ matrix.os }}
          opt:        ${{ matrix.opt }}
          crossopt:   ${{ matrix.crossopt }}
          make_opt:   ${{ matrix.make_opt }}

      - if: (success() || failure()) && (runner.os == 'Windows')
        id: windows_path
        shell: bash
        run: echo "path=$(cat PATH.txt)" >>$GITHUB_OUTPUT

      - if: (success() || failure()) && (runner.os == 'Windows')
        working-directory: "${{ github.workspace }}/fpc/src"
        shell: bash
        run: |
             "${{ github.workspace }}\\fpc\\installed\\bin\\i386-win32\\make.exe" clean all crossinstall CPU_TARGET=${{ matrix.cpu }} OS_TARGET=${{ matrix.os }} PREFIX="${{ github.workspace }}\\bundle-cross\\installed" CROSSOPT="${{ matrix.crossopt }}" OPT="${{ matrix.opt }} ${{inputs.fpc_opt}}" PATH="${{ steps.windows_path.outputs.path }}" ${{ matrix.make_opt }}
             echo "${{ matrix.cpu }}-${{ matrix.os }}" >"${{ github.workspace }}\bundle-cross\info\cross-list.txt"
      
      - if: (success() || failure()) && (runner.os != 'Windows')
        working-directory: "${{ github.workspace }}/fpc/src"
        shell: bash
        run: |
             make clean all crossinstall CPU_TARGET=${{ matrix.cpu }} OS_TARGET=${{ matrix.os }} PREFIX="${{ github.workspace }}/bundle-cross/installed" CROSSOPT="${{ matrix.crossopt }}" OPT="${{ matrix.opt }} ${{inputs.fpc_opt}}"
             echo "${{ matrix.cpu }}-${{ matrix.os }}" >"${{ github.workspace }}/bundle-cross/info/cross-list.txt"
      
      - shell: bash
        run: |
             echo >"${{ github.workspace }}/bundle-cross/fpc.cfg"
             echo "# ${{ matrix.cpu  }}-${{ matrix.os  }}" >>"${{ github.workspace }}/bundle-cross/fpc.cfg"
             echo "#IFDEF cpu${{ matrix.cpu }}" >>"${{ github.workspace }}/bundle-cross/fpc.cfg"
             echo "#IFDEF ${{ matrix.os  }}" >>"${{ github.workspace }}/bundle-cross/fpc.cfg"
      
      - shell: bash
        run: |
             echo "#ENDIF" >>"${{ github.workspace }}/bundle-cross/fpc.cfg"
             echo "#ENDIF" >>"${{ github.workspace }}/bundle-cross/fpc.cfg"

      - name: Tar the cross bundle
        working-directory: "${{ github.workspace }}"
        run: tar -czvf "${{ inputs.bundle_name }}-cross-${{ matrix.cpu }}-${{ matrix.os }}.tar.gz" bundle-cross/*

      - name: Upload the cross bundle
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.bundle_name }}-cross-${{ matrix.cpu }}-${{ matrix.os }}.tar.gz"
          path: "${{ github.workspace }}/${{ inputs.bundle_name }}-cross-${{ matrix.cpu }}-${{ matrix.os }}.tar.gz"

      - name: Upload the cross bundle to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: "${{ inputs.bundle_name }}-cross-${{ matrix.cpu }}-${{ matrix.os }}.tar.gz"
          file: "${{ github.workspace }}/${{ inputs.bundle_name }}-cross-${{ matrix.cpu }}-${{ matrix.os }}.tar.gz"
          file_glob: true

  Aggregate-Cross:
    name: "Aggregate"
    needs: Build-Cross
    if: (success() || failure()) && (inputs.cross != '')
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: ls -R
      - run: make aggregate BUNDLE_NAME=${{ inputs.bundle_name }}

      - name: Upload the bundle
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.bundle_name }}-cross.tar.gz"
          path: "${{ github.workspace }}/${{ inputs.bundle_name }}-cross.tar.gz"

      - name: Upload the bundle to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: "${{ inputs.bundle_name }}-cross.tar.gz"
          file: "${{ github.workspace }}/${{ inputs.bundle_name }}-cross.tar.gz"
          file_glob: true
