name: Planned

on:
  workflow_dispatch:
    inputs:
      release_to:
        description: 'Release to the specified tag (if needed)'
        required: false
        default: ''
      branch:
        required: false
        default: 'fixes_3_2'
      cross:
        required: false
        default: 'planned'
      version:
        required: false
        default: '3.2.3'

jobs:
  Windows:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: windows-latest
      git_branch: ${{ inputs.branch }}
      bundle_name: fpc-${{ inputs.version }}-Windows
      cross: ${{ inputs.cross }}
    secrets: inherit
  Linux:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: ubuntu-latest
      git_branch: ${{ inputs.branch }}
      bundle_name: fpc-${{ inputs.version }}-Linux
      cross: ${{ inputs.cross }}
    secrets: inherit
  macOS:
    uses: ./.github/workflows/build-fpc-bundle-git.yml
    with:
      os: macos-latest
      git_branch: ${{ inputs.branch }}
      bundle_name: fpc-${{ inputs.version }}-macOS
      fpc_opt: "-XR/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
      fpc: system
      cross: ${{ inputs.cross }}
    secrets: inherit
